### ISSUE TITLE
Failed to load the file-mode package

### ISSUE THREAD

**Issue by AndreasTusche** [blezek/file-mode#10]
1. I tried to install file-mode and immediately this error popped up. Hope it helps.

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 7 Enterprise 
**Thrown From**: [file-mode](https://github.com/dblezek/file-mode) package 1.0.1

### Stack Trace

Failed to load the file-mode package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.activate (/packages/file-mode/lib/file-mode.coffee:11:23)
    at /packages/file-mode/lib/file-mode.coffee:32:16)
    at /packages/file-mode/lib/file-mode.coffee:3:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at /app.asar/src/package.js:123:28
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at Package.module.exports.Package.load (/app.asar/src/package.js:110:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/app.asar/src/package-manager.js:468:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:548:30)
    at /app.asar/node_modules/settings-view/lib/package-manager.js:484:29
    at exit (/app.asar/node_modules/settings-view/lib/package-manager.js:99:16)
    at triggerExitCallback (/app.asar/src/buffered-process.js:322:11)
    at /app.asar/src/buffered-process.js:335:11
    at /app.asar/src/buffered-process.js:204:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
     -2:44.1.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-ui.theme-atom-dark-syntax)
```

### Non-Core Packages

```
atom-beautify 0.29.23 
busy-signal 1.4.1 
file-icons 2.1.4 
file-mode 1.0.1 
intentions 1.1.2 
language-todotxt-extended 0.11.0 
linter 2.1.4 
linter-ui-default 1.2.3 
markdown-preview-enhanced 0.12.0 
monokai-seti 0.7.0 
open-recent 5.0.0 
seti-ui 1.7.0 
```

**Comment by AndreasTusche** [comment]
No longer needed.
