### ISSUE TITLE
Failed to load the file-mode package

### ISSUE THREAD

**Issue by msurdi** [blezek/file-mode#8]
[Enter steps to reproduce below:]
1. Update to latest Atom (1.1.0)

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11
**Thrown From**: [file-mode](https://github.com/dblezek/file-mode) package, v1.0.1
### Stack Trace

Failed to load the file-mode package

```
At Cannot read property 'onDidOpen' of null

TypeError: Cannot read property 'onDidOpen' of null
    at Object.module.exports.activate (/Users/msurdi/Dropbox/settings/.atom/packages/file-mode/lib/file-mode.coffee:9:19)
    at Object.<anonymous> (/Users/msurdi/Dropbox/settings/.atom/packages/file-mode/lib/file-mode.coffee:32:16)
    at Object.<anonymous> (/Users/msurdi/Dropbox/settings/.atom/packages/file-mode/lib/file-mode.coffee:3:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:725:34)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "ignoredNames": [
      "*.pyc"
    ],
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
.bin, vundefined
atom-django, v0.3.0
atom-handlebars, v1.2.0
atom-typescript, v7.6.3
autocomplete-python, v0.9.2
bracket-matcher, v0.79.0
color-picker, v2.0.13
docblockr, v0.7.3
file-mode, v1.0.1
language-docker, v1.1.3
language-python-django-templates, v0.1.0
language-spacebars, v0.2.2
linter, v1.9.1
linter-eslint, v3.2.0
linter-jsxhint, v0.1.2
linter-pep8, v1.0.1
linter-tslint, v0.4.2
meteor-api, v2.20.0
pigments, v0.18.1
python-tools, v0.6.5
react, v0.12.10
symbols-tree-view, v0.10.1

# Dev
No dev packages
```

**Comment by klingtnet** [comment]
I can confirm this issue:

**Atom Version**: 1.1.0
**System**: linux 4.2.5-1-ARCH
**Thrown From**: [file-mode](https://github.com/dblezek/file-mode) package, v1.0.1

### Stack Trace

Failed to load the file-mode package

```
At Cannot read property 'onDidOpen' of null

TypeError: Cannot read property 'onDidOpen' of null
    at Object.module.exports.activate (/home/andreas/.atom/packages/file-mode/lib/file-mode.coffee:9:19)
    at Object.<anonymous> (/home/andreas/.atom/packages/file-mode/lib/file-mode.coffee:32:16)
    at Object.<anonymous> (/home/andreas/.atom/packages/file-mode/lib/file-mode.coffee:3:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:725:34)
```

### Commands

```
```

### Config

``` json
{
  "core": {
    "themes": [
      "soda-light-ui",
      "monokai"
    ],
    "audioBeep": false,
    "disabledPackages": [
      "svg-preview",
      "svg-preview"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
asciidoc-preview, v0.6.0
autocomplete-paths, v1.0.2
color-picker, v2.0.13
file-mode, v1.0.1
linter, v1.10.0
linter-rust, v0.2.10
minimap, v4.15.0
monokai, v0.18.0
soda-light-ui, v0.2.0

# Dev
No dev packages
```

**Comment by pdxwolfy** [comment]
Ditto:

[Enter steps to reproduce below:]
1. Attempt to install file-mode

**Atom Version**: 1.4.0
**System**: Mac OS X 10.10.5
**Thrown From**: [file-mode](https://github.com/dblezek/file-mode) package, v1.0.1

### Stack Trace

Failed to load the file-mode package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (/Users/wolfy/.atom/packages/file-mode/lib/file-mode.coffee:11:23)
    at Object.<anonymous> (/Users/wolfy/.atom/packages/file-mode/lib/file-mode.coffee:32:16)
    at Object.<anonymous> (/Users/wolfy/.atom/packages/file-mode/lib/file-mode.coffee:3:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:721:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:117:28
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:443:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:522:30)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:444:29
    at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
  2x -7:59.8.0 window:focus-pane-below (atom-text-editor.editor.is-focused)
     -7:55.4.0 pane:split-down (atom-text-editor.editor.is-focused)
     -7:49.8.0 pane:split-up (atom-text-editor.editor.is-focused)
     -7:22.1.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -7:22.1.0 snippets:expand (atom-text-editor.editor.is-focused)
     -7:22.1.0 editor:indent (atom-text-editor.editor.is-focused)
     -7:20.7.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -7:20 core:undo (atom-text-editor.editor.is-focused)
  2x -6:38.9.0 pane:close (atom-text-editor.editor.is-focused)
     -5:50.9.0 editor:cut-to-end-of-line (atom-text-editor.editor.is-focused)
     -5:49.5.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -5:49.5.0 core:cancel (atom-text-editor.editor.is-focused)
     -5:47.8.0 core:undo (atom-text-editor.editor.is-focused)
     -5:46 pane:split-down (atom-text-editor.editor.is-focused)
     -5:23.2.0 pane:close (atom-text-editor.editor.is-focused)
     -0:17.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

``` json
{
  "core": {
    "closeEmptyWindows": false,
    "disabledPackages": [
      "about",
      "autocomplete-atom-api",
      "autoflow",
      "autosave",
      "background-tips",
      "metrics",
      "timecop",
      "welcome",
      "wrap-guide",
      "archive-view",
      "symbols-view"
    ],
    "ignoredNames": [
      "*.a",
      "*.bak",
      "*.class",
      "*.db",
      "*.dds",
      "*.dll",
      "*.dylib",
      "*.eot",
      "*.exe",
      "*.gif",
      "*.ico",
      "*.idb",
      "*.jar",
      "*.jpeg",
      "*.jpg",
      "*.lib",
      "*.ncb",
      "*.o",
      "*.obj",
      "*.pdb",
      "*.pdf",
      "*.png",
      "*.psd",
      "*.pyc",
      "*.pyo",
      "*.sdf",
      "*.so",
      "*.sublime-workspace",
      "*.suo",
      "*.swf",
      "*.tga",
      "*.ttf",
      "*.zip",
      "*~",
      ".DS_Store"
    ],
    "openEmptyEditorOnStart": false,
    "packagesWithKeymapsDisabled": [
      "advanced-open-file"
    ],
    "projectHome": "/Users/wolfy/Atom"
  }
}
```

### Installed Packages

``` coffee
# User
atom-ctags, v4.4.2
atom-sync, v0.6.0
autoclose-html, v0.19.0
autocomplete-ctags, v0.3.4
chary-tree-view, v0.2.3
color-picker, v2.0.14
file-mode, v1.0.1
language-mason, v2.0.4
less-than-slash, v0.12.0
linter, v1.11.3
linter-perl-check-syntax, v0.2.3
linter-perlcritic, v0.3.1
linter-rubocop, v0.4.7
linter-ruby, v1.2.1
linter-ruby-reek, v1.3.0
multi-wrap-guide, v0.23.5
omni-ruler, v0.4.2
plist-converter, v0.1.2
ruby-block, v0.3.5
run-in-browser, v0.1.3
tab-control, v0.6.9
tab-smart-sort, v0.1.4
tree-view-git-branch, v0.0.6
tree-view-open-files, v0.3.0

# Dev
No dev packages
```
