### ISSUE TITLE
Failed to load - cannot read property 'command' of undefined

### ISSUE THREAD

**Issue by schniedergers** [blezek/file-mode#9]
1. Updated Atom and all packages to latest
2. Starting Atom

**Atom Version**: 1.2.0
**System**: Mac OS X 10.10.5
**Thrown From**: Atom Core
### Stack Trace

Failed to load the file-mode package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (<anonymous>:11:23)
    at Object.<anonymous> (<anonymous>:32:16)
    at Object.<anonymous> (<anonymous>:3:1)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:661:34)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  },
  "editor": {
    "fontSize": 12,
    "invisibles": {},
    "tabLength": 4,
    "fontFamily": "Menlo",
    "lineHeight": 1.35
  }
}
```
### Installed Packages

``` coffee
# User
atomatigit, v1.5.5
auto-indent, v0.5.0
docblockr, v0.7.3
file-mode, v1.0.1
highlight-line, v0.11.0
highlight-selected, v0.10.1
language-groovy, v0.4.0
linter, v1.11.1
linter-pep8, v1.0.1
minimap, v4.16.0
resize-indent, v0.2.1
seti-syntax, v0.4.1
seti-ui, v0.8.1
trailing-spaces, v0.3.2

# Dev
No dev packages
```

**Comment by MarcelRobitaille** [comment]
+1

I am getting the same issue. Seems like this is no longer maintained.

**Comment by AaronDMarasco-VSI** [comment]
Yep. Playing around with this editor for the first time and that greeted me.
